trigger:
- master

pool:
  name: Demo  # Change this to the name of your self-hosted agent pool

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- script: |
    echo "Build, test, and deploy your project here."
    echo "Using a self-hosted agent to bypass hosted parallelism issues."
  displayName: 'Run a multi-line script'
